# Generated by Django 5.0 on 2023-12-31 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('time_duration', models.FloatField()),
                ('is_completed', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('running', 'Running'), ('failed', 'Failed'), ('quit', 'Quit'), ('completed', 'Completed')])),
                ('date_start', models.DateTimeField()),
                ('date_completed', models.DateTimeField()),
                ('notes', models.JSONField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goaltracker.goal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
