# Generated by Django 5.0 on 2023-12-31 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dietplan', '0001_initial'),
        ('goaltracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goaltracker.goal'),
        ),
    ]
